# .circleci/config.yml
version: 2.1

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:1.0.0
    working_directory: ~/repo

jobs:
  terraform-init:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            apk add --no-cache curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
      - run:
          name: Terraform Init
          command: terraform init
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-destroy:
    executor: terraform-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install AWS CLI
          command: |
            apk add --no-cache curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Destroy
          command: terraform destroy -auto-approve

  destroy_infrastructure:
    jobs:
      - terraform-destroy
